# Generated by Django 5.0.6 on 2024-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorGoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на карточку товара')),
                ('price_xpath', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_good_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('minimal_price', models.IntegerField()),
                ('competitor_goods', models.ManyToManyField(related_name='goods', to='app.competitorgoodsmodel', verbose_name='Товары конкурентов')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
