# Generated by Django 5.0.6 on 2024-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorgoodsmodel',
            name='current_price',
            field=models.IntegerField(default=0, verbose_name='Актуальная цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='current_price',
            field=models.IntegerField(default=0, verbose_name='Актуальная цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено в'),
        ),
        migrations.AlterField(
            model_name='competitorgoodsmodel',
            name='price_xpath',
            field=models.CharField(max_length=256, verbose_name='Xpath цены'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='code',
            field=models.CharField(max_length=256, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='competitor_goods',
            field=models.ManyToManyField(blank=True, null=True, related_name='goods', to='app.competitorgoodsmodel', verbose_name='Товары конкурентов'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='minimal_price',
            field=models.IntegerField(verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='store_good_id',
            field=models.IntegerField(unique=True, verbose_name='Id продукта из магазина'),
        ),
    ]
