# Generated by Django 5.0.6 on 2024-07-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kaspigoodsmodel_kaspi_offer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspigoodsmodel',
            name='no_competitors_flag',
            field=models.BooleanField(default=False),
        ),
    ]
