# Generated by Django 5.0.6 on 2024-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_competitorgoodsmodel_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='price_step',
            field=models.IntegerField(default=10, verbose_name='Шаг цены'),
        ),
    ]
