# Generated by Django 5.0.6 on 2024-08-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kaspigoodsmodel_no_competitors_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspigoodsmodel',
            name='prev_price',
            field=models.IntegerField(null=True),
        ),
    ]
