# Generated by Django 5.0.6 on 2024-06-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_goodsmodel_price_step'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='competitorgoodsmodel',
            table='competitor_goods',
        ),
    ]
