# Generated by Django 5.0.6 on 2024-07-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_competitorgoodsmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaspiGoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('prince', models.IntegerField()),
                ('competitors_prices', models.JSONField(verbose_name='Цены конкурентов')),
                ('current_price', models.IntegerField(verbose_name='Актуальная цена')),
                ('min_price', models.IntegerField(verbose_name='Минимальная цена')),
                ('price_step', models.IntegerField(verbose_name='Шаг цены')),
            ],
            options={
                'db_table': 'kaspi_goods',
            },
        ),
    ]
