# Generated by Django 5.0.6 on 2024-07-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_kaspigoodsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaspigoodsmodel',
            name='prince',
        ),
    ]
